### ISSUE TITLE
FF gives "Cross-Origin Request Blocked" error for webfont

### ISSUE THREAD

**Issue by tanelj** [Voog/design-berlin#1]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://fonts.gstatic.com/s/lato/v8/qIIYRU-oROkIk8vfvxw6QvesZW2xOQ-xsNqO47m55DA.woff. This can be fixed by moving the resource to the same domain or enabling CORS.

**Comment by kaspar-naaber** [comment]
Seems to be fixed.
