### ISSUE TITLE
Page header not displayed for public view unless overwritten

### ISSUE THREAD

**Issue by mathias-erik** [Voog/design-berlin#21]
When a new page is created, its title is displayed in the h1 section at the top of the page in the edit-mode. However, when you proceed to preview, its suddenly not displayed.

Edit-mode:
![editmode](https://cloud.githubusercontent.com/assets/6851355/7733050/299127a8-ff35-11e4-9509-57382eccb230.jpg)

Preview:
![previewmode](https://cloud.githubusercontent.com/assets/6851355/7733055/34979c54-ff35-11e4-9567-2d084fd9c684.jpg)

The title only appears to the public eye once overwritten manually. This should be fixed by either stating clear instructions in the placeholder ("Insert site title here") or by leaving it empty in the first place.

**Comment by kaspar-naaber** [comment]
This content area uses {% contentblock %} tags and the described behaviour is the default behaviour of the CMS {% contentblock %} area.
